name: Build JOSS paper pdf

on:
  push:
    branches:
      - paper
  pull_request:
    branches: [ paper ]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build PDF
        uses: openjournals/openjournals-draft-action@1d5c3be74a6a8454854f099d63c6fbb1e8938052
        with:
          journal: joss
          paper-path: ./paper/paper.md
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: ./paper/paper.pdf
