# artifact-upload.yml
---
name: Artifact Upload

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  create-artifact:
    env:
      ARTIFACT_PATH: ./doc/build/
      ARTIFACT_NAME: html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r doc/requirements.txt
      - name: Prepare sphinx build
        run: |
            cd doc
            make html
      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}/${{ env.ARTIFACT_NAME }}
          if-no-files-found: error
